name: "archive"
on:
   workflow_dispatch:
   schedule:
     - cron: "0 * * * *"

concurrency:
   group: ${{ github.ref }}
   cancel-in-progress: false

jobs:
 inits:
    runs-on: ubuntu-latest    
    steps:
      - name: "wait"
        run: sleep 60
        shell: bash

      - uses: actions/checkout@v3
      - name: "instdeps"
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: "connect"
        run: sudo bash ch_prox.sh

      - name: "execute"
        continue-on-error: true
        env:
            fsecret: ${{ secrets.F_SEC }}
            gsecret: ${{ secrets.GIT_TOK }}
        run: bash main.sh "${fsecret}" "${gsecret}"
 
      - name: "cleanups"
        run: |
           sudo kill "$(<openvpn.pid)" || true
           sudo rm -f openvpn.* || true

      - name: update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          repository: .
          file_pattern: .

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
